import Head from "next/head";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    const productGallery = cloudinary.galleryWidget({
      container: "#image-gallery",
      cloudName: "nefejames",
      mediaAssets: [{ tag: "clothes" }],
    });

    productGallery.render();
  }, []);

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Robust Image Gallery</h1>

      <div className="gallery-container">
        <div id="image-gallery"></div>
      </div>
    </div>
  );
}
